version: "2.3"
services:
  rank0:
    image: pytorch-distributed-example
    runtime: nvidia
    networks:
      bridge:
        ipv4_address: 10.1.0.10
    command: python -u main.py --backend nccl --init-method tcp://10.1.0.10:23456 --world-size 2 --rank 0
  rank1:
    image: pytorch-distributed-example
    runtime: nvidia
    networks:
      bridge:
        ipv4_address: 10.1.0.11
    command: python -u main.py --backend nccl --init-method tcp://10.1.0.10:23456 --world-size 2 --rank 1
networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
